# Generated by Django 3.1.4 on 2020-12-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone_num', models.IntegerField(max_length=20)),
            ],
        ),
    ]
